name: amap_base_flutter
description: A new fluttify plugin.
version: 0.0.1
author:  <>
homepage: 

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  foundation_fluttify: ^0.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: me.yohom.amap_base_flutter
    pluginClass: AmapBaseFlutterPlugin